# Full reference https://github.com/foundry-rs/foundry/tree/master/config

[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
gas_reports = ["*"]
optimizer = true
optimizer_runs = 10_000
solc = "0.8.18"

[profile.ci]
fuzz_runs = 10_000
verbosity = 4

[rpc_endpoints]
  ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
  localhost = "http://localhost:8545"
  goerli = "https://goerli.infura.io/v3/${INFURA_API_KEY}"