name: "Deploy Proxy Target"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  RPC_URL_GOERLI: ${{ secrets.RPC_URL_GOERLI }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false
      permit2:
        default: "0x000000000022D473030F116dDEE9F6B43aC78BA3"
        description: 'Permit2 address. Defaults to (0x0000...8BA3)'
        required: false

jobs:
  deploy-proxy-target:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2ProxyTarget contract"
        run: >-
          forge script script/DeployProxyTarget.s.sol
          --broadcast
          --rpc-url "${{ github.event.inputs.chain }}"
          --sig "run(address)"
          -vvvv
          "${{ github.event.inputs.permit2 }}"
      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
