name: "Deploy Batch"

env:
  INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}
  MNEMONIC: ${{ secrets.MNEMONIC }}

on:
  workflow_dispatch:
    chain:
      default: "goerli"
      description: 'Chain name. Defaults to "goerli" if unspecified'
      required: false

jobs:
  deploy-batch:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the BatchStream contract"
        run: >-
          forge script script/DeployBatchStream.s.sol
          --broadcast
          --rpc-url "${{ github.event.inputs.chain }}"
          --sig "run()"
          -vvvv
      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
