name: "Deploy Proxy Target"

env:
  API_KEY_ETHERSCAN: ${{ secrets.API_KEY_ETHERSCAN }}
  MNEMONIC: ${{ secrets.MNEMONIC }}
  RPC_URL_GOERLI: ${{ secrets.RPC_URL_GOERLI }}

on:
  workflow_dispatch:
    inputs:
      chain:
        default: "goerli"
        description: 'Chain name. Defaults to "goerli" if unspecified'
        required: false
jobs:
  deploy-proxy-target:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"
        with:
          submodules: "recursive"
          token: ${{ secrets.CI_TOKEN }}

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Deploy the SablierV2ProxyTarget contract"
        run: >-
          forge script script/DeployProxyTarget.s.sol
          --broadcast
          --rpc-url "${{ inputs.chain }}"
          -vvvv
      - name: "Add summary"
        run: |
          echo "## Deployment result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
